remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-relative-links
relative_links:
  enabled:     true
  collections: false
  exclude: 
    - README.md
exclude: 
  - README.md
title: cissp-notes
description: My personal notes used to prepare for the CISSP.
